name: Build

on: [push]

env:
  PUBLIC_SUPABASE_URL: "${{ secrets.URL }}"
  PRIVATE_SUPABASE_ANON_KEY: "${{ secrets.ANON_KEY }}"
  PRIVATE_SUPABASE_SERVICE_ROLE: "fake_service_role"
  PRIVATE_STRIPE_API_KEY: "fake_stripe_api_key"
  PUBLIC_SITE_NAME: "padeltap"

jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: NPM install
        run: npm install

      - name: SvelteKit Build
        run: npm run build
